name: data-ingest
services:
  ingest:
    restart: unless-stopped
    container_name: dataflow-ingest
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    networks:
      - dataflow
      - mqtt
      - loadbalancer
    environment:
      MQTT_BROKER_URL: $MQTT_BROKER_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    labels:
      - traefik.enable=true
      - traefik.http.routers.dataflow-ingest.rule=Host(`ingest.$DOMAIN`)
      - traefik.http.routers.dataflow-ingest.tls=true
      - traefik.http.routers.dataflow-ingest.tls.domains[0].main=$DOMAIN
      - traefik.http.routers.dataflow-ingest.tls.domains[0].sans=*.$DOMAIN
      - traefik.http.routers.dataflow-ingest.tls.certresolver=letsencrypt
      - traefik.http.routers.dataflow-ingest.entrypoints=websecure
      - traefik.http.services.dataflow-ingest.loadbalancer.server.port=3400
networks:
  dataflow:
    external: true
    name: dataflow
  mqtt:
    external: true
    name: mqtt
  loadbalancer:
    external: true
    name: loadbalancer